apiVersion: v1
kind: Service
metadata:
  name: airflow-svc
  namespace: airflow-k8sexecutor
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31725
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    name: airflow
  sessionAffinity: None
  type: LoadBalancer
